# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_tracking_pb2 as user__tracking__pb2


class CompressServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compress = channel.unary_unary(
                '/compress.service.v1.CompressService/Compress',
                request_serializer=user__tracking__pb2.RequestCompress.SerializeToString,
                response_deserializer=user__tracking__pb2.ResponseCompress.FromString,
                )


class CompressServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Compress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compress': grpc.unary_unary_rpc_method_handler(
                    servicer.Compress,
                    request_deserializer=user__tracking__pb2.RequestCompress.FromString,
                    response_serializer=user__tracking__pb2.ResponseCompress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compress.service.v1.CompressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CompressService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Compress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compress.service.v1.CompressService/Compress',
            user__tracking__pb2.RequestCompress.SerializeToString,
            user__tracking__pb2.ResponseCompress.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DeviceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/compress.service.v1.DeviceService/RegisterDevice',
                request_serializer=user__tracking__pb2.DeviceInfo.SerializeToString,
                response_deserializer=user__tracking__pb2.Device.FromString,
                )


class DeviceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=user__tracking__pb2.DeviceInfo.FromString,
                    response_serializer=user__tracking__pb2.Device.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compress.service.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compress.service.v1.DeviceService/RegisterDevice',
            user__tracking__pb2.DeviceInfo.SerializeToString,
            user__tracking__pb2.Device.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
